<?php
/**
 * File Name: CityModel.php
 * Automatically generated by QGC tool
 * @date: 2021-04-21 16:07:42
 * @version: 4.0.4
 */

namespace qh4module\city\models;


use qttx\web\Model;

/**
 * Class CityModel
 * @package qh4module\city\models
 * @description 数据表tbl_city的Validate模型
 */
class CityModel extends Model
{

    /**
     * {@inheritDoc}
     */
    public function rules()
    {
        return [
			[['id', 'parent_id', 'level', 'level0_id', 'level1_id', 'level2_id', 'level3_id', 'level4_id'], 'integer'], 
			[['name', 'parent_path', 'province', 'city', 'district', 'town', 'pinyin', 'city_code'], 'string', ['max' => 255]],
			[['lng', 'lat'], 'number'], 
			[['char'], 'string', ['max' => 1]]
		];
    }

    /**
     * {@inheritDoc}
     */
    public function attributeLangs()
    {
        return [
			'id' => 'ID', 
			'parent_id' => '上级', 
			'level' => '等级', 
			'name' => '名称', 
			'parent_path' => '所有上级', 
			'province' => '省', 
			'city' => '市', 
			'district' => '区', 
			'town' => '街道', 
			'pinyin' => '拼音', 
			'city_code' => '编码', 
			'lng' => '经度', 
			'lat' => '纬度', 
			'char' => '首字母'
		];
    }
}
