<?php
/**
 * File Name: CityActiveRecord.php
 * Automatically generated by QGC tool
 * @date: 2021-04-21 16:05:34
 * @version: 4.0.4
 */

namespace qh4module\city\models;


use qttx\web\ActiveRecord;

/**
 * Class CityActiveRecord
 * @package qh4module\city\models
 * @description 数据表tbl_project的ActiveRecord模型
 * @property int $id 
 * @property int $parent_id 
 * @property int $level 
 * @property string $name 
 * @property string $parent_path 
 * @property string $province 
 * @property string $city 
 * @property string $district 
 * @property string $town 
 * @property string $pinyin 
 * @property string $city_code 
 * @property double $lng 
 * @property double $lat 
 * @property string $char 
 * @property int $level0_id 
 * @property int $level1_id 
 * @property int $level2_id 
 * @property int $level3_id 
 * @property int $level4_id 
 */
class CityActiveRecord extends ActiveRecord
{
    /**
     * @var string 数据表名
     */
    protected static $table_name = "{{%city}}";

    /**
     * @var string 数据表别名
     */
    protected static $table_alias = "";

    /**
     * 返回数据表的主键
     * @return string
     */
    static function primaryKey()
    {
        return "id";
    }
}
